spring:
  datasource:
    name: datasource
    url: jdbc:mysql://172.16.1.8:3306/test?characterEncoding=utf-8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true