eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  profiles:
    # 读取本地配置文件
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
  application:
    name: config-server